version: 0.0
os: linux
files:
  - source: /Spring3HibernateApp.war
    destination: /opt/tomcat/apache-tomcat-8.5.32/webapps
hooks:
  BeforeInstall:

    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
