version: 0.0
os: linux
files:
  - source: /pom.xml
    destination: /Spring3HibernateApp
#hooks:
#  BeforeInstall:
#    - location: scripts/install_dependencies
#      timeout: 300
#      runas: root
#    - location: scripts/start_server
#      timeout: 300
#      runas: root
#  ApplicationStop:
#    - location: scripts/stop_server
#      timeout: 300
#      runas: root

